### PR TITLE
[11.0][FIX] web_export_view: empty column w/ group by #1099

### LINKED ISSUE #1099: [11.0][BUG] web_export_view: empty column w/ group by on
In any list view with group, if you export view, the excell generated add a void field on header.

contacts odoo

export

Maybe the problem is related with javascript that get header names, and don't take care agout grouping add a void field on header.

https://github.com/OCA/web/blob/11.0/web_export_view/static/src/js/web_export_view.js#L53

### PR DESCRIPTION
**Pull request by Tardo**
Possibly fix #1099

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I think this is happening also in v10, isn't it? Maybe you can provide also the fix there.

**Comment by Tardo** [comment]
@pedrobaeza 10.0 appears to work fine. In 11.0 doesn't work in the same way, can't use "string" property because, for some reason, are not set on all columns (on my tests only in the first) :/

**Comment by pedrobaeza** [comment]
Then is this completed?

**Comment by Tardo** [comment]
For me, yes.

File: web_export_view/static/src/js/web_export_view.js [hunk 1]
```diff
@@ -50,14 +50,16 @@ odoo.define('web_export_view', function (require) {
             var export_columns_names = [];
             var column_index = 0;
```
Comment (yajo) [inline web_export_view/static/src/js/web_export_view.js:55]: Wouldn't it be the same to just put a `1` here? :thinking:

Comment (Tardo) [reply web_export_view/static/src/js/web_export_view.js:55]: Nope :/ The problem is "export_columns_keys"... if you set to 1 in non-grouped views you get an exception... and in grouped you see good headers but bad column content.
This fix really is a "workaround". For me a best solution would be to improve "ListRenderer" and store header strings, avoiding css query selector usage.

**Comment by Tardo** [comment]
Launching flare... What does this PR need to close?

**Comment by pedrobaeza** [comment]
Well, reviewers. I can approve it blindly trusting you, but I prefer @Yajo "JS master" 's opinion

File: web_export_view/static/src/js/web_export_view.js (hunk 1 above)
Comment (yajo) [reply web_export_view/static/src/js/web_export_view.js:55]: This will turn it `1` when it is grouped, and `0` otherwise:

```suggestion
             // Skip 1st empty header cell if list is grouped
             var column_index = view.renderer.state.groupedBy.length && 1;
```

File: web_export_view/static/src/js/web_export_view.js [hunk 2]
```diff
@@ -50,14 +50,16 @@ odoo.define('web_export_view', function (require) {
...
             var column_header_selector;
+            var isGrouped = view.renderer.state.groupedBy.length > 0;
```
Comment (yajo) [inline web_export_view/static/src/js/web_export_view.js:57]: ... then you can remove this change.

File: web_export_view/static/src/js/web_export_view.js [hunk 3]
```diff
@@ -50,14 +50,16 @@ odoo.define('web_export_view', function (require) {
...
             $.each(view.renderer.columns, function () {
                 if (this.tag == 'field' && (this.attrs.widget === undefined || this.attrs.widget != 'handle')) {
                     // non-fields like `_group` or buttons
                     export_columns_keys.push(column_index);
-                    column_header_selector = '.o_list_view > thead > tr> th:not([class*="o_list_record_selector"]):eq('+column_index+')';
+                    var css_selector_index = isGrouped?column_index+1:column_index;
+                    column_header_selector = '.o_list_view > thead > tr> th:not([class*="o_list_record_selector"]):eq('+css_selector_index+')';
```
Comment (yajo) [inline web_export_view/static/src/js/web_export_view.js]: ... and undo this change

File: web_export_view/static/src/js/web_export_view.js [hunk 4]
```diff
@@ -50,14 +50,16 @@ odoo.define('web_export_view', function (require) {
...
                     export_columns_names.push(view.$el.find(column_header_selector)[0].textContent);
                 }
-                column_index ++;
+                ++column_index;
```
Comment (yajo) [inline web_export_view/static/src/js/web_export_view.js:71]: ... and this one too.

**Review by yajo — CHANGES_REQUESTED** [review]
Nothing special, just minifying the diff :blush:

**Review by simahawk — APPROVED** [review]
Approving @Yajo 's version :wink: 
I mean: fix it as he proposed and will be fine.

**Comment by simahawk** [comment]
also, when you fixup pls squash and amend commit msg to contain module's name + upgrade version by 0.0.1. Thanks :)

**Comment by Tardo** [comment]
@Yajo @simahawk the proposed improvement doesn't work properly. Explained in my previous message ;)
All other changes done!

File: web_export_view/readme/ROADMAP.rst [hunk 5]
```diff
@@ -0,0 +1,12 @@
+Known Issues
+============
```
Comment (yajo) [inline web_export_view/readme/ROADMAP.rst]: This header will fail. Remove it.

File: web_export_view/readme/ROADMAP.rst [hunk 6]
```diff
@@ -0,0 +1,12 @@
...
+
+Pedro M. Baeza (pedro.baeza@gmail.com):
```
Comment (yajo) [inline web_export_view/readme/ROADMAP.rst]: wrong email, is `@tecnativa.com`

File: web_export_view/readme/USAGE.rst [hunk 7]
```diff
@@ -0,0 +1,9 @@
+After you installed it, you'll find an additional link 'Export current view'
+right on the sidebar. By clicking on it you'll get a XLS file contains
+the same data of the tree view you are looking at, headers included.
+
+Configuration
+=============
```
Comment (yajo) [inline web_export_view/readme/USAGE.rst]: This header will fail. Use `CONFIGURATION.rst` file instead.

**Review by yajo — CHANGES_REQUESTED** [review]
Yikes, thanks for the README and linter update, although its hard to differentiate now between the real fix to the problem and the cosmetic update. Could you at least split that in 2 commits?

Also, I cannot find the comment where you explain why the suggestion doesn't work. :roll_eyes:

**Comment by Tardo** [comment]
@Yajo done!
Here 🙈: https://github.com/OCA/web/pull/1169#discussion_r253539462

**Review by yajo — APPROVED** [review]

**Review by yajo — CHANGES_REQUESTED** [review]
OK, sorry I had to re-read that answer more slowly; I understand now. Just one more little thing to merge:

File: web_export_view/README.rst [hunk 8]
```diff
@@ -1,81 +1 @@
...
-.. image:: http://odoo-community.org/logo.png
-   :alt: Odoo Community Association
-   :target: http://odoo-community.org
-
-This module is maintained by the OCA.
-
-OCA, or the Odoo Community Association, is a nonprofit organization whose mission is to support the collaborative development of Odoo features and promote its widespread use.
-
-To contribute to this module, please visit http://odoo-community.org.
+This file will be modified by OCA gen-addon-readme script.
```
Comment (yajo) [inline web_export_view/README.rst]: You have 2 options here:

1. Do not touch this file. The bot will generate it after merging.
2. Generate the readme manually and commit it.

But please don't do this. :sweat_smile:

**Review by yajo — CHANGES_REQUESTED** [review]
I had to read more slowly your answer, you're right.

This is ready now, just one minor nitpick. :blush:

File: web_export_view/README.rst (hunk 8 above)
Comment (Tardo) [reply web_export_view/README.rst]: Reverted README modifications ;)

Comment (yajo) [reply web_export_view/README.rst]: Lol, you added a commit to clean up the diff :laughing: 

NP, I fixed it for you. :wink:

**Review by yajo — APPROVED** [review]
