### PR TITLE
[FIX] web_responsive: Chrome slow scroll

### LINKED ISSUE #741: [BUG] web_responsive: App Scroll is Slow on Chrome Mobile
Scrolling of the apps in the app drawer is incredibly slow on Chrome mobile. This can be replicated in the Chrome emulator as well. It is fine on iPhone.

REF Openworx/backend_theme#15

https://youtu.be/ndTXHe-E694

### PR DESCRIPTION
**Pull request by lasley**
Test fix. Do not merge until I give the go-ahead please.

#741

https://github.com/cubiq/iscroll/issues/1100

### CODE REVIEW

**Comment by mgielissen** [comment]
Scrolling works now with Android/Chrome

**Comment by lasley** [comment]
Alright I've applied the same fix without editing the iScroll library, and added a note to the readme to remove the patch once iScroll is updated (this is fixed upstream, but there isn't a new release yet)

**Comment by MosabWadea** [comment]
So I tried this fix but I faced this error, whenever I open the app drawer and close it in the web version:
`Uncaught TypeError: Cannot read property 'options' of undefined
`
```
https://portal.hobbydistrict.com/web/content/3480-c08c6da/web.assets_backend.js:3427
Traceback:
TypeError: Cannot read property 'options' of undefined
    at HTMLBodyElement.setIScrollProbes (https://portal.hobbydistrict.com/web/content/3480-c08c6da/web.assets_backend.js:3427:2011)
    at HTMLBodyElement.dispatch (https://portal.hobbydistrict.com/web/content/2593-8fb4b90/web.assets_common.js:637:451)
    at HTMLBodyElement.elemData.handle (https://portal.hobbydistrict.com/web/content/2593-8fb4b90/web.assets_common.js:610:173)
    at Object.trigger (https://portal.hobbydistrict.com/web/content/2593-8fb4b90/web.assets_common.js:631:211)
    at HTMLBodyElement.<anonymous> (https://portal.hobbydistrict.com/web/content/2593-8fb4b90/web.assets_common.js:682:147)
    at Function.each (https://portal.hobbydistrict.com/web/content/2593-8fb4b90/web.assets_common.js:370:767)
    at jQuery.fn.init.each (https://portal.hobbydistrict.com/web/content/2593-8fb4b90/web.assets_common.js:358:643)
    at jQuery.fn.init.trigger (https://portal.hobbydistrict.com/web/content/2593-8fb4b90/web.assets_common.js:682:118)
    at HTMLBodyElement.triggerOpenedListeners (https://portal.hobbydistrict.com/web/content/3480-c08c6da/web.assets_backend.js:3424:162)
    at HTMLBodyElement.invokeCallbackOnAnimationEnd (https://portal.hobbydistrict.com/web/content/3480-c08c6da/web.assets_backend.js:3424:889)
```

I don't think it is from this fix but maybe I did something wrong or inundated library?

P.S. and the fix didn't work on my phone!

**Comment by pedrobaeza** [comment]
I receive this error when clicking on the icon for showing the drawer, and the clicking outside the drawer (on Firefox on my PC):
```
TypeError: this.iscroll is undefined

http://3306323-742-52282f.runbot3.odoo-community.org/web/content/440-5cf7aed/web.assets_backend.js:3479
Traceback:
setIScrollProbes@http://3306323-742-52282f.runbot3.odoo-community.org/web/content/440-5cf7aed/web.assets_backend.js:3479:1998
dispatch@http://3306323-742-52282f.runbot3.odoo-community.org/web/content/428-7a03819/web.assets_common.js:637:378
add/elemData.handle@http://3306323-742-52282f.runbot3.odoo-community.org/web/content/428-7a03819/web.assets_common.js:610:151
trigger@http://3306323-742-52282f.runbot3.odoo-community.org/web/content/428-7a03819/web.assets_common.js:631:204
trigger/<@http://3306323-742-52282f.runbot3.odoo-community.org/web/content/428-7a03819/web.assets_common.js:682:134
each@http://3306323-742-52282f.runbot3.odoo-community.org/web/content/428-7a03819/web.assets_common.js:370:758
each@http://3306323-742-52282f.runbot3.odoo-community.org/web/content/428-7a03819/web.assets_common.js:358:636
trigger@http://3306323-742-52282f.runbot3.odoo-community.org/web/content/428-7a03819/web.assets_common.js:682:113
triggerOpenedListeners@http://3306323-742-52282f.runbot3.odoo-community.org/web/content/440-5cf7aed/web.assets_backend.js:3476:156
invokeCallbackOnAnimationEnd@http://3306323-742-52282f.runbot3.odoo-community.org/web/content/440-5cf7aed/web.assets_backend.js:3476:880
dispatch@http://3306323-742-52282f.runbot3.odoo-community.org/web/content/428-7a03819/web.assets_common.js:637:378
add/elemData.handle@http://3306323-742-52282f.runbot3.odoo-community.org/web/content/428-7a03819/web.assets_common.js:610:151
```

**Comment by lasley** [comment]
a8f19a8 should fix the issue - my bad I forgot casing

**Comment by pedrobaeza** [comment]
I have tested and now there's no error and scroll in PCs works correctly, but trying on my Android mobile with Chrome, I still need to make funny moves for scrolling: there's no possibility to tap and hold the finger for scrolling. Can you please check it?

**Comment by lasley** [comment]
I stole my girlfriend's Android for the day - should be able to fix this now

**Comment by lasley** [comment]
Alright this last change was working pretty solid for me yesterday and looks good on Runbot now. Someone want to confirm?

Fix was to upgrade iScroll to the bleeding edge revision, which contains the proper change. It was created 10 months ago and there have been no changes, so I figure it's got to be stable enough.

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
Tried and working. There's still a strange effect on the header bar with the logo and the "< Apps" link, but I think it's not related with this issue.

**Review by pedrobaeza — APPROVED** [review]

**Comment by lasley** [comment]
>  There's still a strange effect on the header bar with the logo and the "< Apps" link, but I think it's not related with this issue.

Is it this?

image

**Comment by pedrobaeza** [comment]
Yeah, definitively

**Review by rafaelbn — APPROVED** [review]

**Comment by lasley** [comment]
I can't replicate the header issue with the last commit

File: web_responsive/static/src/js/web_responsive.js [hunk 1]
```diff
@@ -105,12 +105,12 @@ odoo.define('web_responsive', function(require) {
...
                     $(this).find('#appDrawerAppPanelHead').css(
-                        'transform', 'matrix(1, 0, 0, 1, 0, ' + transform + ')'
+                        'marginTop', transform + 'px'
                     );
                 };
                 // Scroll probe aggressiveness level
-                // 2 == always executes the scroll event except during momentum and bounce.
-                this.iScroll.options.probeType = 2;
+                // 1 == The scroll event is fired only when the scroller is not busy doing its stuff.
+                this.iScroll.options.probeType = 1;
```
Comment (lasley) [inline web_responsive/static/src/js/web_responsive.js]: This was actually the fix to the header issue - the transform thing above I realized `marginTop` was more clear & basically the same.

Comment (lasley) [reply web_responsive/static/src/js/web_responsive.js]: Hmmm maybe the marginTop isn't the same, I'm reverting that.

**Comment by pedrobaeza** [comment]
Now it's working worst IMO

**Comment by lasley** [comment]
Damn ok I removed the commits from after you mentioned the other header issue & created #756

**Comment by pedrobaeza** [comment]
OK, merging this then. @angelmoya please take this for v11

**Comment by pedrobaeza** [comment]
Should I squash?

**Comment by lasley** [comment]
> Should I squash?

I went ahead and did it so my GPG is preserved. I'd say we're good for a merge on CI 🍏
