### PR TITLE
Fix [8.0] Perf issue with web_m2x_options #615 

### LINKED ISSUE #615: Perf issue with web_m2x_options
Hello,

Steps to reproduce: 

On a clean base, create a new partner, in Company field enter one character then enter another one, then another one.
6 requests are sent 
- name_search (3 times)
- check_access_rights (3 times)

Expected: 
4 requets: 
- name_search (3 times)
- check_access_rights (1 time)

Depending of the config set, there can be one more extraenous requests after each key press
https://github.com/OCA/web/blob/8.0/web_m2x_options/static/src/js/form.js#L113

Before working on a patch, Is there a reason why this kind of work are processed client side ?

Ping @codingforfun

### PR DESCRIPTION
**Pull request by hparfr**
Before : 
if no options specified after each keystroke, a call to disable_quick_create and/or check_access_rights are made

After:
a call is done once per field

Each request saved improves perf for user and load on the server.

Extra
+ some fixes on `parseInt` : always specify a radix
+ refactor  `is_option_set` 

Fixes #615

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@Yajo please check

File: web_m2x_options/static/src/js/form.js [hunk 1]
```diff
@@ -40,17 +40,12 @@ openerp.web_m2x_options = function (instance) {
...
-                return option === 'true' || option === 'True'
-            } else if (is_bool) {
-                return option
-            }
-            return false
+            //return option in ('True', 'true', true)
+            return {
+                'true': true,
+                'True': true,
+                true: true,
```
Comment (yajo) [inline web_m2x_options/static/src/js/form.js]: This is not doing what you expect. Object keys are never bools, just a `"true"` string.
What you want to do is `return $.inArray(option, [true, "true", "True"])`.

File: web_m2x_options/static/src/js/form.js [hunk 2]
```diff
@@ -70,7 +65,7 @@ openerp.web_m2x_options = function (instance) {
             if (_.isUndefined(this.view))
                     return this._super.apply(this, arguments);
                 if (!_.isUndefined(this.view.ir_options['web_m2x_options.limit'])) {
-                this.limit = parseInt(this.view.ir_options['web_m2x_options.limit']);
+                this.limit = parseInt(this.view.ir_options['web_m2x_options.limit'],10);
```
Comment (yajo) [inline web_m2x_options/static/src/js/form.js:73]: According to [MDN docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseInt#Parameters), please revert this change.

File: web_m2x_options/static/src/js/form.js [hunk 3]
```diff
@@ -291,7 +287,7 @@ openerp.web_m2x_options = function (instance) {
             // returned.
 
             if (!_.isUndefined(this.view.ir_options['web_m2x_options.limit'])) {
-                this.limit = parseInt(this.view.ir_options['web_m2x_options.limit']);
+                this.limit = parseInt(this.view.ir_options['web_m2x_options.limit'], 10);
```
Comment (Yajo) [inline web_m2x_options/static/src/js/form.js]: As said above, revert this.

File: web_m2x_options/static/src/js/form.js [hunk 4]
```diff
@@ -401,7 +397,7 @@ openerp.web_m2x_options = function (instance) {
                     .css('cursor', 'pointer')
                     .click(function(e)
                     {
-                        var id = parseInt(jQuery(this).attr('data-id'));
+                        var id = parseInt(jQuery(this).attr('data-id'), 10);
```
Comment (Yajo) [inline web_m2x_options/static/src/js/form.js]: Revert this.

**Review by yajo — CHANGES_REQUESTED** [review]
The idea is good, but you still need to change some things.

File: web_m2x_options/static/src/js/form.js (hunk 2 above)
Comment (hparfr) [reply web_m2x_options/static/src/js/form.js:73]: According to MDN: 
>Always specify this parameter to eliminate reader confusion and to guarantee predictable behavior.

Comment (yajo) [reply web_m2x_options/static/src/js/form.js:73]: Oops sorry, I mistaked the diff, somehow it was in my mind that you were *removing* it, while you were adding it. Then for get my comments about this 😅

File: web_m2x_options/static/src/js/form.js (hunk 1 above)
Comment (hparfr) [reply web_m2x_options/static/src/js/form.js]: True, I will revert it.

**Review by yajo — APPROVED** [review]
Will squash at merge.

**Review by jesusVMayor — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Does it happen also in 9.0/10.0?

**Comment by hparfr** [comment]
Thanks guys :)
