### PR TITLE
[IMP] web_responsive: Document Viewer key events

### LINKED ISSUE #1476: [12.0] web_responsive: document viewer not closed with Esc when maximized
Steps to reproduce:

- Preview an image attachment clicking on it.
- Maximize it with the corresponding button.
- Press "Esc".
- It doesn't close the preview. On not maximized and with standard, it closes it.

### PR DESCRIPTION
**Pull request by Tardo**
This fixes #1476 changing key events listeners to main events instead of widget events.

PDF Viewer uses iframe and Odoo bus doesn't listen events from there. Can't use 'Document Viewer' keybinds when the active element is the PDF Viewer.

cc @Tecnativa

### CODE REVIEW

File: web_responsive/static/src/js/web_responsive.js [hunk 1]
```diff
@@ -529,12 +529,27 @@ odoo.define('web_responsive', function (require) {
 
     // DocumentViewer: Add support to maximize/minimize
     DocumentViewer.include({
-        events: _.extend(DocumentViewer.prototype.events, {
+        events: _.extend(_.omit(DocumentViewer.prototype.events, [
+            'keydown',
```
Comment (yajo) [inline web_responsive/static/src/js/web_responsive.js:537]: I'd appreciate a comment explaining why are you modifying these events behavior.

**Review by yajo — APPROVED** [review]

**Comment by Tardo** [comment]
Done

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
/ocabot merge patch

As said, please move all of this to v13
